apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expense-dynamic-sc
reclaimPolicy: Retain
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer