apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0a7d760ea50c4a088

---
#Claim 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: efs-app
  namespace: expense
  labels:
    component: nginx-static
    project: expense
    tier: nginx-static
spec:
  containers:
  - name: nginx-app
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/bin/nginx/html/
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-static-claim
---
apiVersion: v1
kind: Service
metadata:
  name: static-volume
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    component: nginx-static
    project: expense
    tier: nginx-static
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80