---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dynamic-sc
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic
  namespace: expense
  labels: 
    component: nginx-dynamic
    project: expense
    tier: nginx-dynamic
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-claim
---

apiVersion: v1
kind: Service
metadata:
  name: static-volume
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    component: nginx-dynamic
    project: expense
    tier: nginx-dynamic
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
