apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course 
      valueFrom:
        configMapKeyRef:
          name: config-demo          # The ConfigMap this value comes from.
          key: course # The key to fetch.
    - name: projectname 
      valueFrom:
        configMapKeyRef:
          name: config-demo          # The ConfigMap this value comes from.
          key: projectname