piVersion: v1
kind: Pod
metadata:
  name: secret-config-file
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: Secret-key         # The ConfigMap this value comes from.
