apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  namespace: expense
spec:
  ports:
  - prtocol: TCP
    port: 80
    targetport: 80 # coatainer port (Nginx)
  selector:
    name: nginx-clusterip
  type: ClusterIP