apiVersion: v1
kind: Pod
metadata:
  name: nginx
  Namespace: expense
  label:
    envirnmennt: dev
    module: front-back
    project: expense

spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80