apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  selector:
    envirnmennt: dev
    module: front-back
    project: expense
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
