apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: ninx
    project: expense
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: ninx
      project: expense
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx