apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: ninx-deployment
    project: expense
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ninx-deployment
      project: expense
  template:
    metadata:
      labels:
        app: ninx-deployment
        project: expense
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80