# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend
#   namespace: expense
# data:
#   DB_HOST: mysql # here we are giving the service name given in mysql yaml
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fronend-deployment
  namespace: expense
  labels:
    component: frotend
    project: expense
    tier: frotend
spec:
  replicas: 2
  selector:
    matchLabels:
      component: frotend
      project: expense
      tier: frotend
  template:
    metadata:
      labels:
        component: frotend
        project: expense
        tier: frotend
    spec:
      containers:
      - name: backend
        image: joindevops/frontend:v1.0
        # envFrom:
        # - configMapRef:
        #     name: backend   


---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  selector:
    component: frotend
    project: expense
    tier: frotend
  ports:
  - name: frontend
    protocol: TCP
    port: 80
    targetPort: 80