apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: expense
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: 10
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1.0
        ports:
        - containerPort: 3306
